experiment:
  dataset: amazon_music
  data_config:
    strategy: fixed
    train_path: ../data/amazon_music/train.tsv
    validation_path: ../data/amazon_music/validation.tsv
    test_path: ../data/amazon_music/test.tsv
  binarize: True
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG, Recall, HR, MAR, Gini, SEntropy, EFD, EPC, ACLT, APLT, PopREO, PopRSP]
    complex_metrics:
      - metric: UserMADranking
        clustering_name: WarmColdUsers
        clustering_file: ../data/amazon_music/u_clusters.tsv
      - metric: UserMADrating
        clustering_name: WarmColdUsers
        clustering_file: ../data/amazon_music/u_clusters.tsv
      - metric: BiasDisparityBD
        user_clustering_name: WarmColdUsers
        user_clustering_file: ../data/amazon_music/u_clusters.tsv
        item_clustering_name: ItemPopularity
        item_clustering_file: ../data/amazon_music/i_clusters.tsv
    paired_ttest: True
    wilcoxon_test: True
  print_results_as_triplets: True
  external_models_path: ../external/models/__init__.py
  models:
    MultiVAE:
      meta:
        validation_rate: 1
        verbose: True
        save_recs: True
        validation_metric: nDCG@10
        optimize_internal_loss: False
      lr: [0.01, 0.001] #0.002718457840118028
      epochs: 100
      intermediate_dim: [100, 200, 300] #91
      latent_dim: [50, 100, 200, 300] #100
      batch_size: -1
      dropout_pkeep: [0.8, 1]
      reg_lambda: 0 #[0, 0.01]
      early_stopping:
        patience: 10
        verbose: True
        monitor: nDCG@10